import type { AccessGrant, AccessReviewEvent, AccessTeam, AccessUser, TeamMembership } from "./types.js";

const createdAt = "2026-05-31T00:00:00.000Z";

export const defaultAccessUsers: AccessUser[] = [
  { id: "usr-admin-prototype", actorKey: "admin:prototype", displayName: "Prototype Admin", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-admin-reviewer", actorKey: "admin:reviewer", displayName: "Prototype Admin Reviewer", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-cm-prototype", actorKey: "cm_cell:prototype", displayName: "CM Cell Prototype Officer", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-verification-prototype", actorKey: "verification:prototype", displayName: "Verification Prototype Officer", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-minister-prototype", actorKey: "minister:prototype", displayName: "Minister Prototype User", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-dept-officer-prototype", actorKey: "department_officer:prototype", displayName: "Department Officer Prototype User", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-mla-prototype", actorKey: "mla:prototype", displayName: "MLA Prototype User", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-councillor-prototype", actorKey: "councillor:prototype", displayName: "Councillor Prototype User", status: "active", mfaState: "not_required_mvp", createdAt },
  { id: "usr-worker-prototype", actorKey: "worker:prototype", displayName: "MVP Worker", status: "active", mfaState: "not_required_mvp", createdAt },
];

export const defaultAccessTeams: AccessTeam[] = [
  { id: "team-admin", name: "Whistle Admin Operators", role: "admin", status: "active", ownerActorKey: "admin:prototype", defaultScopeKind: "system", defaultScopeValue: "whistle", createdAt },
  { id: "team-cm-cell", name: "CM Cell Command", role: "cm_cell", status: "active", ownerActorKey: "cm_cell:prototype", defaultScopeKind: "state", defaultScopeValue: "Tamil Nadu", createdAt },
  { id: "team-verification", name: "Ticket Verification Team", role: "verification", status: "active", ownerActorKey: "verification:prototype", defaultScopeKind: "queue", defaultScopeValue: "verification", createdAt },
  { id: "team-min-maws", name: "MAWS Minister Team", role: "minister", status: "active", ownerActorKey: "minister:prototype", defaultScopeKind: "ministry", defaultScopeValue: "Municipal Administration and Water Supply", createdAt },
  { id: "team-dept-maws", name: "MAWS Department Officer Queue", role: "department_officer", status: "active", ownerActorKey: "department_officer:prototype", defaultScopeKind: "ministry", defaultScopeValue: "Municipal Administration and Water Supply", createdAt },
  { id: "team-mla-velachery", name: "Velachery MLA Team", role: "mla", status: "active", ownerActorKey: "mla:prototype", defaultScopeKind: "constituency", defaultScopeValue: "Velachery", createdAt },
  { id: "team-ward-48", name: "Ward 48 Local Owner", role: "councillor", status: "active", ownerActorKey: "councillor:prototype", defaultScopeKind: "ward", defaultScopeValue: "Ward 48", createdAt },
  { id: "team-workers", name: "Whistle MVP Workers", role: "worker", status: "active", ownerActorKey: "admin:prototype", defaultScopeKind: "system", defaultScopeValue: "jobs", createdAt },
];

export const defaultTeamMemberships: TeamMembership[] = [
  { id: "mship-admin", userId: "usr-admin-prototype", teamId: "team-admin", roleLabel: "Admin operator", createdAt },
  { id: "mship-admin-reviewer", userId: "usr-admin-reviewer", teamId: "team-admin", roleLabel: "Second approver", createdAt },
  { id: "mship-cm", userId: "usr-cm-prototype", teamId: "team-cm-cell", roleLabel: "Escalation officer", createdAt },
  { id: "mship-verification", userId: "usr-verification-prototype", teamId: "team-verification", roleLabel: "Verifier", createdAt },
  { id: "mship-minister", userId: "usr-minister-prototype", teamId: "team-min-maws", roleLabel: "Minister office", createdAt },
  { id: "mship-dept-officer", userId: "usr-dept-officer-prototype", teamId: "team-dept-maws", roleLabel: "Department operations officer", createdAt },
  { id: "mship-mla", userId: "usr-mla-prototype", teamId: "team-mla-velachery", roleLabel: "Constituency coordinator", createdAt },
  { id: "mship-councillor", userId: "usr-councillor-prototype", teamId: "team-ward-48", roleLabel: "Local owner", createdAt },
  { id: "mship-worker", userId: "usr-worker-prototype", teamId: "team-workers", roleLabel: "Worker", createdAt },
];

export const defaultAccessGrants: AccessGrant[] = [
  {
    id: "grant-admin",
    targetType: "team",
    targetId: "team-admin",
    role: "admin",
    scopeKind: "system",
    scopeValue: "whistle",
    protectedAccess: true,
    reporterIdentity: true,
    actions: [
      "admin.config.read",
      "admin.config.write",
      "admin.config.approve",
      "access.manage",
      "dashboard.explain",
      "ticket.create",
      "audit.read",
      "audit.export",
      "notifications.outbox.read",
      "observability.metrics.read",
      "jobs.sla_escalations.run",
      "jobs.evidence_scans.run",
      "jobs.notifications.run",
    ],
    createdAt,
  },
  {
    id: "grant-cm-cell",
    targetType: "team",
    targetId: "team-cm-cell",
    role: "cm_cell",
    scopeKind: "state",
    scopeValue: "Tamil Nadu",
    protectedAccess: true,
    reporterIdentity: true,
    actions: [
      "dashboard.read",
      "dashboard.explain",
      "verification.queue",
      "ticket.read",
      "evidence.read",
      "evidence.upload_session",
      "evidence.upload_complete",
      "audit.read",
      "audit.export",
      "notifications.outbox.read",
      "observability.metrics.read",
      "agent.recommendation.run",
      "field.action.write",
      "rejection.review.write",
    ],
    createdAt,
  },
  {
    id: "grant-verification",
    targetType: "team",
    targetId: "team-verification",
    role: "verification",
    scopeKind: "queue",
    scopeValue: "verification",
    protectedAccess: true,
    reporterIdentity: true,
    actions: [
      "verification.queue",
      "verification.decision",
      "ticket.create",
      "ticket.read",
      "evidence.read",
      "evidence.upload_session",
      "evidence.upload_complete",
      "audit.read",
      "notifications.outbox.read",
      "dashboard.explain",
      "agent.recommendation.run",
    ],
    createdAt,
  },
  {
    id: "grant-minister-maws",
    targetType: "team",
    targetId: "team-min-maws",
    role: "minister",
    scopeKind: "ministry",
    scopeValue: "Municipal Administration and Water Supply",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["dashboard.read", "dashboard.explain", "ticket.read", "evidence.read", "agent.recommendation.run", "field.action.write"],
    createdAt,
  },
  {
    id: "grant-minister-rural-development",
    targetType: "team",
    targetId: "team-min-maws",
    role: "minister",
    scopeKind: "ministry",
    scopeValue: "Rural Development & Panchayat Raj",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["dashboard.read", "dashboard.explain", "ticket.read", "evidence.read", "agent.recommendation.run", "field.action.write"],
    createdAt,
  },
  {
    id: "grant-minister-food-civil-supplies",
    targetType: "team",
    targetId: "team-min-maws",
    role: "minister",
    scopeKind: "ministry",
    scopeValue: "Cooperation, Food and Consumer Protection",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["dashboard.read", "dashboard.explain", "ticket.read", "evidence.read", "agent.recommendation.run", "field.action.write"],
    createdAt,
  },
  {
    id: "grant-dept-officer-maws",
    targetType: "team",
    targetId: "team-dept-maws",
    role: "department_officer",
    scopeKind: "ministry",
    scopeValue: "Municipal Administration and Water Supply",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["dashboard.read", "dashboard.explain", "ticket.read", "evidence.read", "evidence.upload_session", "evidence.upload_complete", "field.action.write"],
    createdAt,
  },
  {
    id: "grant-mla-velachery",
    targetType: "team",
    targetId: "team-mla-velachery",
    role: "mla",
    scopeKind: "constituency",
    scopeValue: "Velachery",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["dashboard.read", "dashboard.explain", "ticket.read", "field.action.write"],
    createdAt,
  },
  {
    id: "grant-councillor-ward-48",
    targetType: "team",
    targetId: "team-ward-48",
    role: "councillor",
    scopeKind: "ward",
    scopeValue: "Ward 48",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["dashboard.read", "dashboard.explain", "ticket.read", "field.action.write"],
    createdAt,
  },
  {
    id: "grant-worker",
    targetType: "team",
    targetId: "team-workers",
    role: "worker",
    scopeKind: "system",
    scopeValue: "jobs",
    protectedAccess: false,
    reporterIdentity: false,
    actions: ["jobs.sla_escalations.run", "jobs.evidence_scans.run", "jobs.notifications.run"],
    createdAt,
  },
];

export const defaultAccessReviewEvents: AccessReviewEvent[] = [
  {
    id: "access-review-seed",
    actor: "system",
    action: "access.seed",
    summary: "Seeded MVP prototype access users, teams, memberships, and grants.",
    createdAt,
  },
];
