import type { AdminConfigSnapshot, AppControlConfig, CategoryConfig, CategoryReadiness, SlaPolicy } from "./types.js";

export const defaultCategories: CategoryConfig[] = [
  { id: "corruption", labelEn: "Corruption", labelTa: "ஊழல்", sensitivity: "protected", enabled: true },
  { id: "roads", labelEn: "Roads", labelTa: "சாலைகள்", sensitivity: "identity_masked", enabled: true },
  { id: "water", labelEn: "Water", labelTa: "தண்ணீர்", sensitivity: "identity_masked", enabled: true },
  { id: "power", labelEn: "Power", labelTa: "மின்சாரம்", sensitivity: "identity_masked", enabled: true },
  { id: "sanitation", labelEn: "Sanitation", labelTa: "சுகாதாரம்", sensitivity: "identity_masked", enabled: true },
  { id: "safety", labelEn: "Public Safety", labelTa: "பொது பாதுகாப்பு", sensitivity: "identity_masked", enabled: true },
  { id: "health", labelEn: "Health", labelTa: "சுகாதார சேவை", sensitivity: "identity_masked", enabled: true },
  { id: "education", labelEn: "Education", labelTa: "கல்வி", sensitivity: "identity_masked", enabled: true },
  { id: "revenue", labelEn: "Revenue", labelTa: "வருவாய்", sensitivity: "identity_masked", enabled: true },
  { id: "ration", labelEn: "Ration / PDS", labelTa: "ரேஷன் / பொது விநியோகம்", sensitivity: "identity_masked", enabled: true },
  { id: "other", labelEn: "Other", labelTa: "மற்றவை", sensitivity: "identity_masked", enabled: true },
];

export const defaultSlaPolicies: SlaPolicy[] = [
  { stage: "verification", label: "Verification SLA", durationDays: 2, escalationTarget: "Verification lead", enabled: true },
  { stage: "local", label: "Local / MLA SLA", durationDays: 7, escalationTarget: "Assigned ministry", enabled: true },
  { stage: "ministry", label: "Ministry SLA", durationDays: 10, escalationTarget: "CM Cell", enabled: true },
  { stage: "cm_cell", label: "CM Cell intervention SLA", durationDays: 7, escalationTarget: "CM Cell Director", enabled: true },
  { stage: "rejection_review", label: "Rejection review SLA", durationDays: 3, escalationTarget: "CM-maintained review lead", enabled: true },
];

export const defaultCategoryReadiness: CategoryReadiness[] = [
  {
    categoryId: "corruption",
    primaryOwner: "Protected Screening / CM Cell",
    slaSummary: "State-configured protected screening before any wider routing",
    escalationPath: "Protected screening -> CM Cell/protected authority",
    roleAccess: ["Verification", "CM Cell", "Protected Review"],
    publicVisibility: "No raw public visibility; aggregate-only after policy approval",
    privacyLevel: "protected",
    sopStatus: "scheduled",
    trainingStatus: "scheduled",
    launchState: "pilot_only",
    notes: "Keep protected-only until legal, vigilance, evidence, and safety SOPs are approved.",
  },
  {
    categoryId: "roads",
    primaryOwner: "Local/MLA, then Highways or Local Body",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "Local/MLA -> Ministry -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Core civic launch category.",
  },
  {
    categoryId: "water",
    primaryOwner: "Local/MLA, then MAWS",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "Local/MLA -> Municipal Administration and Water Supply -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Core civic launch category.",
  },
  {
    categoryId: "power",
    primaryOwner: "Local/MLA, then Energy Department",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "Local/MLA -> Energy Department -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Core civic launch category.",
  },
  {
    categoryId: "sanitation",
    primaryOwner: "Local/MLA, then MAWS or Local Body",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "Local/MLA -> Municipal Administration and Water Supply -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Core civic launch category.",
  },
  {
    categoryId: "safety",
    primaryOwner: "Verification-approved public safety authority",
    slaSummary: "State-configured based on severity",
    escalationPath: "Verification -> Approved authority -> CM Cell",
    roleAccess: ["Verification", "Restricted Owner", "CM Cell"],
    publicVisibility: "V2 aggregate only with thresholds",
    privacyLevel: "identity_masked",
    sopStatus: "scheduled",
    trainingStatus: "scheduled",
    launchState: "pilot_only",
    notes: "Pilot with restricted SOP because public-safety reports can be sensitive.",
  },
  {
    categoryId: "health",
    primaryOwner: "Health Department / District health office",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "District health office -> Health Department -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Launch-ready for facility and service-delivery issues, not medical emergencies.",
  },
  {
    categoryId: "education",
    primaryOwner: "School Education / Local education office",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "Local education office -> Education Department -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Launch-ready for school infrastructure and service issues.",
  },
  {
    categoryId: "revenue",
    primaryOwner: "Revenue Department / District administration",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "District administration -> Revenue Department -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Launch-ready for patta, certificate, and local office service-delay issues.",
  },
  {
    categoryId: "ration",
    primaryOwner: "Food and Civil Supplies / PDS",
    slaSummary: "2d verification, 7d local, 10d ministry",
    escalationPath: "Local PDS owner -> Food and Civil Supplies -> CM Cell",
    roleAccess: ["Verification", "MLA", "Minister", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "approved",
    trainingStatus: "approved",
    launchState: "ready",
    notes: "Launch-ready for ration shop access, stock, and service issues.",
  },
  {
    categoryId: "other",
    primaryOwner: "Verification determines owner",
    slaSummary: "State-configured after intake classification",
    escalationPath: "Verification -> Assigned owner -> Ministry/CM Cell",
    roleAccess: ["Verification", "Assigned Owner", "CM Cell"],
    publicVisibility: "V2 aggregate only",
    privacyLevel: "identity_masked",
    sopStatus: "scheduled",
    trainingStatus: "scheduled",
    launchState: "pilot_only",
    notes: "Use as controlled intake until category routing quality is proven.",
  },
];

export const defaultAppControls: AppControlConfig[] = [
  { id: "privacy-local", group: "Privacy", name: "Mask identity below ministry", value: true, valueType: "boolean", critical: true },
  { id: "protected-bypass", group: "Protected", name: "Corruption bypasses local routing", value: true, valueType: "boolean", critical: true },
  { id: "notify-sms", group: "Notifications", name: "SMS stage updates", value: true, valueType: "boolean", critical: false },
  {
    id: "notify-template",
    group: "Notifications",
    name: "Citizen stage template",
    value: "Ticket {{ticketId}} moved to {{currentQueue}}.",
    valueType: "string",
    critical: false,
  },
  { id: "lang-tamil", group: "Language", name: "Tamil citizen copy", value: true, valueType: "boolean", critical: false },
  { id: "citizen-phone-otp-required", group: "Privacy", name: "Citizen phone OTP required", value: false, valueType: "boolean", critical: false },
  { id: "official-user-otp-required", group: "Privacy", name: "Government user login OTP required", value: false, valueType: "boolean", critical: true },
  { id: "identity-gov-id-policy-mode", group: "Privacy", name: "Citizen government ID policy mode", value: "phone-otp-only", valueType: "string", critical: true },
  { id: "identity-gov-id-required-categories", group: "Privacy", name: "Government ID required categories", value: "none", valueType: "string", critical: true },
  { id: "identity-gov-id-provider-config-ref", group: "Infrastructure", name: "Government ID provider/policy reference", value: "not-enabled-for-mvp1", valueType: "string", critical: true },
  { id: "platform-postgres-migration-evidence-ref", group: "Infrastructure", name: "Postgres migration evidence reference", value: "artifact://whistle/mvp1/postgres-migration/local-uat-assumed", valueType: "string", critical: true },
  { id: "platform-postgres-mvp-check-evidence-ref", group: "Infrastructure", name: "Postgres MVP check evidence reference", value: "artifact://whistle/mvp1/postgres-mvp-check/local-uat-assumed", valueType: "string", critical: true },
  { id: "feature-public", group: "Feature Flags", name: "Public aggregate insights", value: true, valueType: "boolean", critical: false },
  { id: "public-publish-delay-hours", group: "Feature Flags", name: "Public insight publication delay", value: 24, valueType: "number", critical: false },
  { id: "public-cell-threshold", group: "Privacy", name: "Public small-cell suppression threshold", value: 2, valueType: "number", critical: false },
  { id: "feature-agent-intake", group: "Feature Flags", name: "Recommend-only intake agent", value: true, valueType: "boolean", critical: false },
  { id: "ops-maintenance", group: "Operations", name: "Maintenance mode", value: false, valueType: "boolean", critical: false },
  { id: "asset-logo-approved", group: "Operations", name: "Owned Whistle prototype logo selected", value: true, valueType: "boolean", critical: true },
  { id: "asset-portrait-approved", group: "Operations", name: "Public figure portrait replaced by neutral asset", value: true, valueType: "boolean", critical: true },
  { id: "asset-tn-emblem-approved", group: "Operations", name: "Government emblem replaced by neutral civic mark", value: true, valueType: "boolean", critical: true },
  { id: "asset-public-disclaimer-approved", group: "Operations", name: "Public disclaimer wording approved", value: true, valueType: "boolean", critical: true },
  { id: "infra-official-oidc-config-ref", group: "Infrastructure", name: "Official OIDC/MFA config reference", value: "pending-secret-manager-ref", valueType: "string", critical: true },
  { id: "infra-official-oidc-mfa-ready", group: "Infrastructure", name: "Official OIDC/MFA provider ready", value: false, valueType: "boolean", critical: true },
  { id: "infra-worker-auth-config-ref", group: "Infrastructure", name: "Worker auth secret reference", value: "pending-secret-manager-ref", valueType: "string", critical: true },
  { id: "infra-worker-auth-ready", group: "Infrastructure", name: "Worker service authentication ready", value: false, valueType: "boolean", critical: true },
  { id: "infra-citizen-otp-config-ref", group: "Infrastructure", name: "Citizen OTP/SMS provider reference", value: "pending-provider-contract-ref", valueType: "string", critical: true },
  { id: "infra-citizen-otp-provider-ready", group: "Infrastructure", name: "Citizen OTP/SMS provider ready", value: false, valueType: "boolean", critical: true },
  { id: "infra-evidence-storage-config-ref", group: "Infrastructure", name: "Evidence storage/KMS/scanner reference", value: "pending-security-approval-ref", valueType: "string", critical: true },
  { id: "infra-evidence-storage-ready", group: "Infrastructure", name: "Evidence storage, scanning, and KMS ready", value: false, valueType: "boolean", critical: true },
  { id: "infra-notification-provider-config-ref", group: "Infrastructure", name: "Notification provider reference", value: "pending-provider-contract-ref", valueType: "string", critical: true },
  { id: "infra-notification-provider-ready", group: "Infrastructure", name: "Notification provider contracts ready", value: false, valueType: "boolean", critical: true },
  { id: "infra-rate-limit-config-ref", group: "Infrastructure", name: "Distributed rate-limit provider reference", value: "pending-platform-approval-ref", valueType: "string", critical: true },
  { id: "infra-distributed-rate-limit-ready", group: "Infrastructure", name: "Distributed public rate limiting ready", value: false, valueType: "boolean", critical: true },
  { id: "infra-deployment-observability-config-ref", group: "Infrastructure", name: "Deployment/SIEM/telemetry reference", value: "pending-ops-evidence-ref", valueType: "string", critical: true },
  { id: "infra-deployment-runbook-ready", group: "Infrastructure", name: "Deployment, backup, and SIEM runbook ready", value: false, valueType: "boolean", critical: true },
  { id: "uat-launch-rehearsal-evidence-ref", group: "Operations", name: "MVP1 rehearsal evidence reference", value: "artifact://whistle/mvp1/rehearsal-packet/local-uat-assumed", valueType: "string", critical: true },
  { id: "uat-citizen-lifecycle-rehearsed", group: "Operations", name: "Citizen submit and track rehearsal complete", value: false, valueType: "boolean", critical: true },
  { id: "uat-verification-sop-approved", group: "Operations", name: "Verification SOP and training approved", value: false, valueType: "boolean", critical: true },
  { id: "uat-role-dashboard-rehearsed", group: "Operations", name: "Role dashboard rehearsal complete", value: false, valueType: "boolean", critical: true },
  { id: "uat-protected-track-sop-approved", group: "Operations", name: "Protected-track SOP approved", value: false, valueType: "boolean", critical: true },
  { id: "uat-defect-register-ref", group: "Operations", name: "MVP1 defect register reference", value: "artifact://whistle/mvp1/defect-register/local-uat-assumed", valueType: "string", critical: true },
  { id: "uat-open-blocker-defects", group: "Operations", name: "Open blocker UAT defects", value: 0, valueType: "number", critical: true },
  { id: "uat-open-critical-defects", group: "Operations", name: "Open critical UAT defects", value: 0, valueType: "number", critical: true },
  { id: "uat-open-major-defects", group: "Operations", name: "Open major UAT defects", value: 0, valueType: "number", critical: true },
  { id: "uat-open-minor-defects", group: "Operations", name: "Open minor UAT defects", value: 0, valueType: "number", critical: false },
  { id: "uat-defect-triage-ready", group: "Operations", name: "MVP1 defect triage queue accepted", value: false, valueType: "boolean", critical: true },
  { id: "ops-restore-drill-evidence-ref", group: "Operations", name: "Restore drill evidence reference", value: "artifact://whistle/mvp1/restore-drill/local-uat-assumed", valueType: "string", critical: true },
  { id: "ops-restore-drill-signed-off", group: "Operations", name: "Production-like restore drill signed off", value: false, valueType: "boolean", critical: true },
  { id: "ops-siem-worm-evidence-ref", group: "Operations", name: "SIEM/WORM export evidence reference", value: "artifact://whistle/mvp1/siem-worm-export/local-uat-assumed", valueType: "string", critical: true },
  { id: "ops-siem-worm-signed-off", group: "Operations", name: "SIEM/WORM export signed off", value: false, valueType: "boolean", critical: true },
  { id: "ops-telemetry-launch-watch-evidence-ref", group: "Operations", name: "Telemetry launch watch evidence reference", value: "artifact://whistle/mvp1/telemetry-launch-watch/local-uat-assumed", valueType: "string", critical: true },
  { id: "ops-telemetry-launch-watch-signed-off", group: "Operations", name: "Telemetry launch watch signed off", value: false, valueType: "boolean", critical: true },
  { id: "ops-origin-allowlist-evidence-ref", group: "Operations", name: "Browser origin allowlist evidence reference", value: "artifact://whistle/mvp1/origin-allowlist/local-uat-assumed", valueType: "string", critical: true },
  { id: "ops-origin-allowlist-signed-off", group: "Operations", name: "Browser origin allowlist signed off", value: false, valueType: "boolean", critical: true },
  { id: "ops-incident-hold-policy-evidence-ref", group: "Operations", name: "Incident hold policy evidence reference", value: "artifact://whistle/mvp1/incident-hold-policy/local-uat-assumed", valueType: "string", critical: true },
  { id: "ops-incident-hold-policy-signed-off", group: "Operations", name: "Incident hold conditions signed off", value: false, valueType: "boolean", critical: true },
];

export function defaultAdminConfig(): AdminConfigSnapshot {
  return {
    categories: defaultCategories.map((item) => ({ ...item })),
    readiness: defaultCategoryReadiness.map((item) => ({ ...item, roleAccess: [...item.roleAccess] })),
    slaPolicies: defaultSlaPolicies.map((item) => ({ ...item })),
    appControls: defaultAppControls.map((item) => ({ ...item })),
  };
}
